-- MySQL
SELECT CITY, CHARACTER_LENGTH(CITY) FROM STATION GROUP BY CITY ORDER BY CHARACTER_LENGTH(CITY), CITY ASC LIMIT 1;
SELECT CITY, CHARACTER_LENGTH(CITY) FROM STATION GROUP BY CITY ORDER BY CHARACTER_LENGTH(CITY) DESC LIMIT 1;
