/* MS SQL Server */
SELECT TOP 1 CITY, LEN(CITY) FROM STATION GROUP BY CITY ORDER BY LEN(CITY), CITY ASC LIMIT 1;
SELECT TOP 1 CITY, LEN(CITY) FROM STATION GROUP BY CITY ORDER BY LEN(CITY) DESC LIMIT 1;
