-- MySQL
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%a'
UNION
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%e'
UNION
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%i'
UNION
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%o'
UNION
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%u';
